### ISSUE TITLE
Error "No Checkpoint file found" while running cell detection

### ISSUE THREAD

**Issue by bencheikhb1** [qalid7/compath#1]
I'm having the following error when I try to run this: 

**/compath-master/cell_detect$ python Generate_Output_Main_Davros.py --data_dir=./data --sub_dir_name=./results**

where **./data** contains a .jpg image and parameters-detection.txt and **./results** is an empty folder.

Traceback (most recent call last):
  File "Generate_Output_Main_Davros.py", line 78, in <module>
    post_process=True)
  File "D:\Bureau\compath-master\compath-master\cell_detect\sccnn_detection.py", line 67, in generate_output_sub_dir
    post_process=post_process)
  File "D:\Bureau\compath-master\compath-master\cell_detect\subpackages\generate_output.py", line 156, in generate_output_sub_dir
    assert ckpt, "No Checkpoint file found"
AssertionError: No Checkpoint file found

Can you provide two command line examples for detection and classification using you code?

Thank you

**Comment by fractal-rb** [comment]
Hello, 

I've been trying to execute this code for research purposes similar H&E stained images but encounter various errors on running the subroutines. Going over the README file again there is mention of a "main run script" but don't seem to see it anywhere in the repository. 

Iterating what was mentioned above a a few lines as example to execute the code will be much appreciated.

Thanks!
